### ISSUE TITLE
Egpu/GPUs implemetation

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#336]
I was wondering if you had plans to use egpu or gpu for hardware recode acceleration in the future?

**Comment by mackworth** [comment]
That’s really a question for the ffmpeg and handbrake folks, as they provide the software cTiVo uses to do the actual encoding.  It’s been a while since I looked into this, but ffmpeg still says “Hardware encoders typically generate output of significantly lower quality than good software encoders like x264, but are generally faster and do not use much CPU resource. (That is, they require a higher bitrate to make output with the same perceptual quality, or they make output with a lower perceptual quality at the same bitrate.)”. (But I think that’s an old note)

There’s more information available here, if you want to experiment.
https://trac.ffmpeg.org/wiki/HWAccelIntro

Looks like you can just add `-hwaccel` to the video options to try hw video decoding

You can use activity monitor to tell if it’s actually in use:
https://developer.apple.com/documentation/metal/tools_profiling_and_debugging/gpu_activity_monitors/monitoring_your_mac_s_gpu_activity/

Looks like there’s some work in progress at Handbrake:
https://github.com/HandBrake/HandBrake/pull/1522

If you do experiment, let me know if you see any benefit.

**Comment by tdlivings** [comment]
Thank you for the info. I have been monitoring the various canned outputs including protest lt and the el gato h264 and they are all cpu driven. The disk cost of a prores is about 4x and a usual 8 gb file blossoms into a 30 go but is faster than an mp4 output. That is ok until one considers a week of output for 40 shows is 1.2 tb. There is a setting to prefer egpu in Mojave’s but is a program doesn’t us gpu to start with it is useless. 

Thank you again. I will try the hwaccel option soon.

**Comment by mackworth** [comment]
Of course, the best option is not to transcode at all. Decrypt MP4 just copies the stream into a new file. This works great, except that iTunes and QuickTime Player don’t like interpolated streams. So 720p works fine, but 1080i fails. IIRC, VLC works though. Haven’t tried Plex.

**Comment by mackworth** [comment]
FYI, if you have a T2 mac (e.g. Touch bar macbooks), then there is a hardware enabled version that you can try.  

See this discussion: #343

**Comment by tdlivings** [comment]
Thank you
