### ISSUE TITLE
Encode problem in 3.1.2

### ISSUE THREAD

**Issue by rqchin** [mackworth/cTiVo#342]
I have some shows that have encode problems. The odd thing is that of the six episodes of the show, only two had failures. Can you help me figure out what is happening and what I should adjust?
[com.cTiVo.cTiVo 2018-11-05 06-30 copy.log](https://github.com/mackworth/cTiVo/files/2549322/com.cTiVo.cTiVo.2018-11-05.06-30.copy.log)

**Comment by mackworth** [comment]
Sorry for lengthy delay here. Mostly because I don't have much to suggest based on the log, other than trying 3.2, which has a newer version of ffmpeg and to try one of the Handbrake formats.

**Comment by rqchin** [comment]
OK, I've installed 3.2b3 and I'll see how it goes.

**Comment by mackworth** [comment]
In supporting someone else, I noticed that the channel was marked as H.264 so the shows were being downloaded as Transport Stream, but they were really MP2 files, which can lead to corruption. I'm going to add a warning or something, but this could easily be your issue. In Edit>Channels, check that (a) Always Use Transport Stream is off and (b) that UseTS for the channel of these shows is marked as No (empty check box).

**Comment by rqchin** [comment]
Just a follow-up and clarification for this. Should every channel have UseTS off?
![ctivochannels](https://user-images.githubusercontent.com/33967440/52602560-2628e400-2e31-11e9-8341-d8e6a5a8bbf8.jpg)

**Comment by mackworth** [comment]
So the - is a “don’t know”. Blank is No and Check is yes.

**Comment by rqchin** [comment]
So preferably all channels are blank in that column, right?

**Comment by mackworth** [comment]
So for this testing, yes. What you have there looks like you deleted all the channels, leaving you with just the the default SkipMode-known channels, so cTiVo currently knows nothing about H264 or TS status of any channel.  So, for those channels that had an encode 

 The default behavior of previous cTiVo versions would switch to TS once it saw a H264, and never switch back. The next beta version of cTiVo will be enforcing no MPEG2 over TS, so always MPEG2 over PS and H264 over TS, as I've just found it to be too high a probability of corrupting the stream otherwise.

**Comment by rqchin** [comment]
Hmmm, I didn't knowingly delete all the channels. Is there something I should do to add the others back?

**Comment by mackworth** [comment]
Nothing needed. It will just keep track of what it sees as you download shows.

**Comment by mackworth** [comment]
Give 3.3.0beta1 a try; it has a good chance of fixing this problem.
