### ISSUE TITLE
Newest Macs (with T2 chip) and hardware acceleration

### ISSUE THREAD

**Issue by mackworth** [mackworth/cTiVo#343]
So the latest Macs have the T2 security chip, and it apparently provides tremendously fast compression, even H.265.  If you have one of these, and are willing to do some tests, let me know, and I'll send you a Format to experiment with.

From Apple:
These Mac computers have the Apple T2 Security Chip:

- iMac Pro
- 2018 Mac mini models
- 2018 MacBook Air models
- 2018 MacBook Pro models 

You can also use System Information to learn whether your Mac has this chip:
Press and hold the Option key while choosing Apple () menu > System Information.
In the sidebar, select either Controller or iBridge, depending on the version of macOS in use.
If you see "Apple T2 chip" on the right, your Mac has the Apple T2 Security Chip.

**Comment by sugyfelix** [comment]
I have a shiny new MacMini & MacBook Air both with T2. 

Also, have some free time to experiment...

**Comment by mackworth** [comment]
Congratulations!

Here's a prototype Format.  No idea if it will work.  One uses ffmpeg directly, the other uses the Default script to allow EDLs.  Use the Direct one first.
Use File>Import Formats to load.
You may want to set AdvPrefs> Don't Delete tmp files, to see what ffmpeg says about the process. You'll need to look in the temp directory (click on the Temp Files Directory field and then the header bar pulldown to see where that is).
[HEVC.plist.zip](https://github.com/mackworth/cTiVo/files/2569815/HEVC.plist.zip)

**Comment by sugyfelix** [comment]
I was already starting to play with ffmpeg directly on some TiVo downloads using some Googled tips...

I think you might need some bash-foo on ffmpeg_edl_ac3.sh ...

The "-vcodec hvec_videotoolbox -vtag hvc1” options have to come after the "-i <input-file>” otherwise you get a "Unknown decoder ‘hevc_videotoolbox’”.

It appears that ffmpeg_edl_ac3.sh does some magic with the parameters that can’t seem to be corrected by putting the video options in a different field (or editing formats has some magic about using an old setting.)

If you add “—allow_sw true” after the hevc_videotoolbox you can play around using the software only implementation. Its much slower but will allow you to move forward.

On another note, using no audio codec or just using “-acodec aac” gives QuickTime error -50 on playback.

Either adding "-ac 2" or "-ac 6” after "-acodec aac" seems to make it playable.

Only other interesting thing I found was a way to resolve some ugly artifacts by increasing bufsize & maxrate to 9M. Its a year old so might not mean anything anymore.

—-   Derek

**Comment by sugyfelix** [comment]
I should have remembered that, but its been a while since I played around with cTiVo…

Anyway, seems to work fine!

I tried a progressive channel, an interlaced channel and an x264 channel (which seems to get coded as 1080p30? by my cable company, so I guess that qualifies as progressive.)

Commercial cutting seems to work fine.

On my basic MacBook Air I was encoding hour long shows in 8-10 minutes with 20% cpu load.

One run on my basic MacMini was a little over 2x faster.

Quality seems less than the software encoder. Trying some experiments to see what options can effect the quality. Not much documentation on any of this. Only clue you get is ffmpeg complaining that some option that you typed in was not consumed by any codec.

— Derek

**Comment by mackworth** [comment]
Great!  Let me know what recommendations you have for Format(s) to include in the next release.
Can you do a H.264 hardware-assisted compression, or just HEVC?

**Comment by sugyfelix** [comment]
h264_videotoolbox also available. This has a few more documented tuning options.

Might want to include the “-allow_sw true” option so that someone who picks the format will still function on a non-T2 machine. T2 machines always use the hardware no matter the allow_sw setting. I’ve seen an error implying T2 busy. It comes up on non T2 machines without allow_sw that says hardware not available or busy. Might be a limit to simultaneous encodes on T2 machines.

**Comment by mackworth** [comment]
So if you allow 2 simultaneous encoders in cTiVo with allow_sw, does one use hardware acceleration and the other use software?

On the audio, which setting did you settle on?  The odd thing is that the script is supposed to add  `-ac:a:0 2` after the audio invocation `-c:a:0 aac`, so that should come out to the same thing as `-ac 2`, but limited to the first audio stream. Have you looked at the ffmpeg command line invocation to see what the difference between them is?

**Comment by sugyfelix** [comment]
Haven’t tried any simultaneous encodes, yet ... putting out a few fires today...

The dual streams created by the FFmpeg script worked fine. Both were created and could be selected. It’s something weird about the default if nothing is specified.

Was going to ask you about Handbrake but noticed you had been poking them earlier. Seems like they have some fixes ready to pull to enable T2 support. Would be nice since FFmpeg always gets out of sync because of stream errors, but Handbrake cruises on with no problems.

**Comment by sugyfelix** [comment]
I tried a few tests with using ffmpeg directly…

First use gets the T2. Others get software. This is without any allow_sw setting. So it seems to just fallback silently and slowly...

**Comment by sugyfelix** [comment]
On T2 Mac’s, it seems like allow_sw defaults to on. 

On my MacMini, the T2 hardware seems to be 3-4x faster than software. Maybe on machines with more cores the software would close the gap. CPU load for the hardware is low, maybe 20% or less, so a lot of time is left for software.

My plan is to just use T2 hardware for my typical 2-4 shows per night. Waiting for Handbrake guys to pull support for T2 machines. FFmpeg glitches the audio and typically the audio sync multiple times per hour on my Cox channels. My 2 x264 channels seem to be better when using FFmpeg, but I haven’t tried going down the route of selecting a different encoder by channel.

Still investigating quality issues. Found a few hints about knobs not available on FFmpeg that could help. 

In general it’s very sparsely documented, and seems more trial and error with the VideoToolBox API. 

In general it seems like you need a higher bitrate using T2 hardware than software to get closer to similar quality.

P.S. I’ll be on vacation for 3 weeks, so no experiments from my end for a bit...

**Comment by sugyfelix** [comment]
An update on Mac with T2.

Have done some googling, source reading and experimenting to come up with the following state of affairs:

ffmpeg 4.0.1 uses the following for x265

-c:v hevc_videotoolbox -vtag hvc1

    the following options seem to have an effect:

        -b:v <n>                Set video bit rate
        -g <n>                  Set gop size

ffmpeg uses the following for x264

-c:v h264_videotoolbox

    the following options seem to have an effect:

        -b:v <n>k
        -g n
        -profile:b main|high    Set profile

Handbrake version 1.2.0 has T2 support.  

JSON “VideoEncoder”: “vt_h264” or CLI —encoder vt_h264 for x264

     only JSON “VideoAvgBitrate”: n  or CLI —vb n has any effect
 
JSON “VideoEncoder”: “vt_h265" or CLI -encoder vt_h265 for x265 

     only JSON “VideoAvgBitrate”: n  or CLI —vb n has any effect

Handbrake using vt_h265 logs a whole bunch of errors, but the video is playable…
Track status with https://github.com/HandBrake/HandBrake/issues/1689 <https://github.com/HandBrake/HandBrake/issues/1689>

In general the T2 encoder seems to infer a bitrate from the width x height of the output. Tends to pick a too low of a bitrate for smaller frame sizes.

The -g and -profile settings seem to have a very minor effect on picture quality but reduce the video size by about 1%.

**Comment by sugyfelix** [comment]
Noticed that Handbrake has fixed the problem with hevc with T2.

===================================
Closed #1689 via #1806.
===================================

Current Handbrake version 1.2 works for encoder vt_h264 and I assume next version should include changes for encoder vt_h265 problem.

I ended up debugging the problem since they don't seem to have many people with Macs with T2 chip. I’m currently using my own build of Handbrake to test out vt_264/5 on my cTiVo downloads...

Sent from my iPad

**Comment by mackworth** [comment]
So do you have Formats that I should include with cTiVo to take advantage of these? From your work, it sounds like one could use either ffmpeg or HB, and that if one is looking for H.265, then the Format should use HW if available and fall back to SW. So that might be four new Formats: Default HW, Default HEVC,  HB Default HW, HB HEVC?

**Comment by mackworth** [comment]
Not embedded in a beta yet. @sugyfelix has been working on this, which can be enabled with a Format, and I'm eagerly waiting for him to propose ones to include in the beta.

**Comment by tdlivings** [comment]
Thank you

**Comment by tdlivings** [comment]
I have been using prefer egpu in app settings

**Comment by sugyfelix** [comment]
I’ve been away for a couple of weeks...may be able to get around to this weekend...

**Comment by mackworth** [comment]
Hint hint: I would still like to add this to cTiVo...

**Comment by tdlivings** [comment]
Sounds good to me. I have a blackmagic just waiting for work.

**Comment by sugyfelix** [comment]
Hasn't seemed like a year...

I finally got around to looking at this again. After reviewing my old notes and playing around a little with the latest HB 1.3.2 I have at the least some recommendations:

When one uses the hardware encoders in the T2 chips there are not many tuning options available. About the only thing that can be set that effects the encoding speed and/or quality is the video bit rate "--vb n"  (where n is implicitly kb.) 

The way I've been using the T2 is to modify the HB format to include the following:

1)  In "Video Options for Encoder" after the -Z"prefix": add --encoder vt_h264 or --encoder vt_h265 (this selects the hardware accelerated versions of h264 or h265, it also overrides anything selected in the JSON description.)

2)  If the format uses the -2 or --two-pass:  add --no-two-pass because the hardware doesn't support 2 pass. It just does 2 one passes! So this saves half the encoding time. I've only noticed this on 4K HEVC formats. It seems safe to always include this if using the hardware encoders.

3)  If your resulting file doesn't look so good: add an explicit --vb n to force a video bitrate. The T2 encoders seem to read some tea leaves to determine the value the they will use. I've noticed that the input .mpg TiVo file is always determined to be a 200kb source. I don't if this is a HB bug or if the T2 encoders even have access to this. Some of the times I encode to 432p30 (i.e 768x432) for small devices. At this resolution the T2 encoders pick 256kb as the video bitrate. Something like 800-900kb gives a reasonably good picture. So I override the --vb on this size. 

So I can see this being included in cTiVo either via some more HB defaults (starts to get unwieldy I could imagine.)

 Or, maybe have a GUI option to enable T2 acceleration and have it appended some additional T2 options to formats that are enabled for T2 acceleration and when T2 acceleration is enabled. This would mostly hide the T2 from the user. Only problem would be adding having to add "--vb n" when things look bad. I guess this may be the case for a custom HB override.

Note: FFmpeg has T2 support also, but I haven't really done much with it because FFMpeg encoding fails over 50% of the time because it either fails with a decoding error, or creates output files with out of sync video/audio when it skips minor decoding errors. I get a ~1 in a 1000 failure rate using HB.

**Comment by tannebil** [comment]
I have a 2018 Mac Mini with the i5. I ran a lot of downloads last fall using both ffmpeg and Handbrake using variations on test formats that Hugh was gracious enough to create for me. Unfortunately, I keep coming to the same conclusion which was that it added little value to cTiVo for me (a great disappointment). Hugh encouraged me to write up my results but every time I started, I ended up wanting to run more tests and could never get to closure. :-)

My cTiVo objective is to produce a single output file at looks good on all my devices (LG OLED65C7 w/ATV4K, iPad Pro 11", Mac Mini with 1920x1200 screen, 2014 MacBook Pro 15", iPhone 11). I used to use a lot of different formats but I find that the cTiVo Default format seems to work best for me these days. File sizes are around 1GB/hour

Low-bit rate encode quality was consistently abysmal and to get an output file that was quality equivalent to he "Default" formal required accepting a 30-40% larger file. It would run in half the time but I regularly get 2x real-time on Default and don't have any problem getting my downloading done overnight so it just didn't seem worth taking the compatibility hit from H.265 on older devices or the increase in required disk space. The only time I use a T2 encode with cTivo is when I'm traveling and recording sports on an MPEG2 channel where I'll accept the lower quality at the same bit rate to get a 4 hour game a few hours earlier. And since Comcast as switched to all MPEG4 on my system in April, that might not still be the right trade-off (I'll know once live sports resumes).

I do regularly use T2 H.265 encoding with Blu-Ray rips when I want a high quality/high bit-rate encode that I'm going to keep. I ripped the Lord of the Rings Blu-Ray at 1080p with a file size around 3GB/hour using Handbrake GUI and the results look terrific on my LG OLED65C7.

Encode times varied fairly dramatically between ffmpeg, Handrake, and Compressor as it appears there still a substantial amount of the encoding process that is not hardware-assisted. The best results I got at lower bit rates were with the Handbrake GUI but clock time that was almost as long as Default with about the same file size so I never pursued building an testing a cTiVo format.

Another limitation is that cTiVo queue processing means that if you want to guarantee that the T2 gets used, you have to limit concurrent encoding to a single show. That means losing some throughput because cTiVo can't download the next show until the current show finishes encoding. You can't really use the same format for both software and hardware encodes because the quality and run-tine deltas are just too large. 

I can see a couple of use cases where T2 encodes would be useful.

1. If you want near-original quality especially of high-bit rate MPEG2 shows

2. If you are using a dual core or slow CPU Mac with cTiVo and your storage needs are minimal or (speculative) only want "good enough" for an iPhone file.

In contrast to sugyfelix, I found ffmpeg to be somewhat more reliable than Handbrake but more importantly, it was consistently faster. However I never got an encode that didn't have unacceptable levels of artifacting at anything below about -vb 1400. But based on his comments maybe I'll give Handbrake another try.

**Comment by tannebil** [comment]
Finally got back to it. I did some testing using an episode of Seal Team (1080p, MPEG4) and NCIS LA (720p, MPEG2).

First, the video quality of the hardware assisted encodes was inferior to the video quality from the software H.264 Default format at the same file sizes. It's most noticeable when motion stops, e.g. a head turns and it does a small jump blur when it stops. Not unwatchable noticeable on even my 24" 1920x1200 monitor. I tried a number of runs starting at about 1200 Kbps and ending at 1600 Kbps. It got better as the bit rate went up but that blur never went away.

The video options lines were:

Default HW H.265 (ffmpeg)
<<<INPUT>>> -vcodec hevc_videotoolbox -vtag hvc1 -b:v 1600k -bufsize 1600k -allow_sw 1 -profile:v main  -vf "yadif,scale=w=floor(iw*min(1\,min(1280/iw\,720/ih))/2)*2:h=-2"

Default HB H.265 HW (Handbrake)
-Z"Apple 720p30 Surround" --encoder vt_h265 --encopts allow_sw=1 --no-two-pass

L to R the values are resolution, video rate (Mediainfo), file size, encoding time. 

You can see the improvements in encoding but, at least in my use case with this Mac, it's not enough to offset the loss in quality except in an edge case where I wanted to result as quickly as possible. I don't know how that result scales so maybe the calculation changes for someone using a T2 Macbook Air.

The one anomalous result that I don't understand is the time on the HB encode of the NCIS LA episode. I repeated it just to confirm it was correct. It's almost like it ignored the --no-two-pass argument but when use the preset in Handbrake with two passes, the quality is much better. More investigation is required. 

Results

NCIS LA MPEG2: 1080i, 11.7 Mbps 5.66 GB
Default H.264: 720p, 1348 Kbps, 857 MB, 38:13
Default HW H.265 (1600 Kbps): 720p, 1622 Kbps. 982 MB, 15:29 
Default HB HEVC (1600 Kbps): 720p, Kbps. 957 MB, 30:28

Seal Team H.264: 720p, 5858 Kpbs, 2.87 GB
Default H.264: 720p, 1666 Kbps, 1.00 GB, 44:48
Default HW H.265 (1600 Kbps): 720p, 1846 Kbps, 1.09 GB, 16:00
Default HB HVEC (1600 Kbps): 720p, 1595 Kbps. 984 GB, 16:54

**Comment by mackworth** [comment]
Well, I’m going to close this out as proper M1 support will obviate the not great results we’ve seen from T2.

**Comment by mackworth** [comment]
Bill (et al), looks like Handbrake has improved the situation here.  Here's a couple of Formats to try and see what you think:  
[HB HW Formats.plist.zip](https://github.com/mackworth/cTiVo/files/10960955/HB.HW.Formats.plist.zip)

**Comment by mackworth** [comment]
Sorry, typo in that one: here's a revised version:
[HB HW Formats](https://github.com/mackworth/cTiVo/files/10961453/HB.HW.Formats2.plist.zip)

**Comment by tannebil** [comment]
Thanks. Sorry for the delay but I've been traveling. 

The new formats are working well. I'm currently watching a basketball game in Buenos Aires on an ATV that was encoded using the "HB HW Small". It's a 2 Mbps stream being played using Plex from my Studio back home in the US.

The "HB HW" format works fine but the bit rate is higher (5-6 Mbps) than my connection can handle and the Plex on-the-fly transcoding results in lots of pauses and a video quality worse than the small format. I think it's more a Plex transcoding issue than a format issue as the regular format works fine the LAN without transcoding. Plex currently only transcodes to H.264.

One thing I noticed is that these formats are slower than the ones I've configured. I suspect the ones you built are using two-pass encoding and mine only are one-pass. But the format is still pretty fast on my Studio so it's a good trade-off for me. Somebody on a slower server may find it too slow but single-pass encoding results in noticeably worse quality.

**Comment by tannebil** [comment]
Also, it bugs me unreasonably that the description for the "HB HW Small" format says "poor quality". It's actually pretty good even watching action scenes in a basketball game. Maybe "reduced" or "fair" would be a better term as it's very watchable. I've shifted all my sports to it.
