### ISSUE TITLE
Large files when decrypted to TiVo/MP4 are often truncated

### ISSUE THREAD

**Issue by penguinlust** [mackworth/cTiVo#352]
I've got several files that if I re-encode to default they are fine but if I try to just dump the raw tivo format they get truncated if they hit an error in the base mpeg2 format. If there's a bad packet the program should just keep going -- truncated files are far worse than a bad packet or two

**Comment by penguinlust** [comment]
I did one to MP4 format. All the failures happened on "Decrypted TiVo Show" as well as the one that was done to MP4 (you're right in that it didn't make a difference. However, a bad packet table in MP4 could be expected if there's an error -- that's not true in the case of the base TiVo format (MPEG 2) as they are discreet packets.

**Comment by mackworth** [comment]
It's difficult for Decrypted TiVo Show to get (or write) less data than Default, as the same flow is used in both cases, except that after receiving and decrypting the file, Default then calls ffmpeg (in a complex batch file process) on the file, and Decrypted just writes it to disk.

On the other hand, before that happens, the decryption process itself can definitely fail due to glitches, potentially skipping sections or truncating the file, but that would affect downloads in both Formats. If this were the case, you might try tivoLibre decoding in Adv Prefs, but that requires Java to be installed on your Mac.

If you temporarily enable "Don't delete tmp files" in Adv Prefs and do a Default download, then you will see the bufferSHOWNAME.mpg file in your temporary directory, which should be exactly the file that is saved by Decrypted.

Hmm, any chance cTiVo has changed from PS to TS underneath your tests? (If it detects an MP4 stream trying to be downloaded with PS (ie no video stream present, just an audio stream), then it auto-shifts to TS and tries again.) If you look in the log, you'll see the exact URL being sent, which will include the "&Format=video/x-tivo-mpeg-ts" if it's a TS transfer. You'll also see the exact configs.  

If none of these help, if you could set debug level to Major, and run a download first with Decrypted and then Default, and post the result, I'll see what I can find.

**Comment by mackworth** [comment]
Any luck?

**Comment by mackworth** [comment]
Give 3.3.0beta 1 a try, it may help on this, due to problems with MP2 over TS.

**Comment by penguinlust** [comment]
Thanks. Been on the road for the past few weeks -- will try when I get back.

Eric
