### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#360]
I am using the canned output options like ProRes LT and HB 1080 and the program deletes the SRT at the end. I know they are embedding the closed captions but for FCPX edits it would be nice to retain that file.

Thank you

**Comment by mackworth** [comment]
(Didn't get an email on this one, sorry for delay.)

Because I wasn't sure if anyone was using it, I actually left in the preference, when I took out the GUI option. So you should be able to copy/paste into Console:
`defaults write com.ctivo.ctivo KeepSRTs -bool YES`

Although the code is there, I admit I haven't tested this, so let me know if it works for you.

**Comment by tdlivings** [comment]
Will do thank you

**Comment by mackworth** [comment]
Presuming that that works, I'll close this for now.

**Comment by tdlivings** [comment]
It worked!

Thank you

**Comment by mackworth** [comment]
Thanks for confirming. I’ve added it to the Advanced page on the wiki
