### ISSUE TITLE
New TiVo SkipMode marks episodes 100% viewed on Tivo

### ISSUE THREAD

**Issue by scottsisco** [mackworth/cTiVo#362]
First, I would like to say I love the integration of Tivo Skipmode. However, I have noticed after it runs it marks the episode as 100% viewed on the Tivo. Is it possible to have cTiVo restore the original view state after skip mode runs?

**Comment by mackworth** [comment]
So, in general, it does do that, or should. It notes the current position and restores it afterwards.  Just tried 3.3.0 release with three different shows, and it's still working fine on mine.  

Let me be really pedantic to be sure I understand. These are shows that prior to SkipMode retrieval have not been viewed on the TiVo at all (viewed on its attached TV to be precise), and then after SkipMode retrieval, when you go to play them on the TiVo, you see them cued up at or near the end of the show? Same thing if you have a partially viewed show (say paused after 5 minutes)?

Which TiVo do you have? Assuming that it's yes to both above, can you set up a show cued up a few minutes in, then...
1) Do a control-click on the show in cTiVo and "Reload all Info" (which will erase the SkipMode data already retrieved, then...
2) go to Preferences>Advanced, and set the log level (near the bottom) of TiVoRPC to Verbose. Then close that, and ...
3) do a control-click-Get SkipMode From Tivo; wait for it to finish.
4) turn off Verbose (back to Normal)
5) Go to Help>Show logs in Finder to find the latest Log
6) Validate where in the show TiVo has it paused
6) Post that log here, so I can see if there's any errors in the "conversation"

**Comment by scottsisco** [comment]
Wow, thanks for your quick response! I am using a TiVo Roamio.

>  These are shows that prior to SkipMode retrieval have not been viewed on the TiVo at all (viewed on its attached TV to be precise), and then after SkipMode retrieval, when you go to play them on the TiVo, you see them cued up at or near the end of the show? Same thing if you have a partially viewed show (say paused after 5 minutes)?

Correct, the shows have not been viewed on the TiVo at all. It is **not** the case that when I go to play them after the SkipMode retrieval completes that they are cued up at the end or near the end of the show, but rather the show's progress bar in the TiVo interface shows, I should have been clearer about this, that the show has already been viewed up to the end. When I play the episode it begins at the beginning of the episode like I would expect. 

The progress bar is a useful visual representation of what episodes my wife and I have already viewed on the TiVo and that will get a little bit tricky if all the episodes are marked with a 100% viewed progress bar after CTiVo makes a copy each night. I hope this all makes sense. 

I am happy to do some testing when I get home from work in a few hours. I really love your app I have been using it for years now.

**Comment by mackworth** [comment]
So, the blue TiVo progress bar (the one at the folder level, as opposed to the green one during a show) has many known problems. At the moment, mine is not showing at the My Shows level for any show, but does show inside a subfolder for all shows. So in those folders, I did check and on my machine, it restores both progress bars correctly, whether a show is at the beginning or in the middle.  And your green bar is correct, so that suggests that cTiVo is restoring the pause point properly. So I'm thinking the disconnect between your two bars is a TiVo problem, and rebooting your TiVo MAY help (doesn't fix my top-level problem, for example).  (BTW, do you find a difference within a subfolder versus at the top level?)

if not, then I'm happy to review the log as I mentioned above.

**Comment by scottsisco** [comment]
My Tivo shows the blue progress bar at the my shows level and at the subfolder show level for all shows. 

I rebooted my TiVo then I picked an episode of Supernatural that I know I had not seen that was at 100% on the progress bar. I started the episode from the beginning and fast forwarded to about the 1 minute mark. I then went to cTiVo and reloaded all info for the episode. I then ran skip mode again and the TiVo did its thing, but once it finished gathering the skip mode data the episode started playing the Supernatural episode at the 36 minute make and I'm assuming would have played to the end of the episode if I had not stopped it. This would maybe explain why I was seeing the full progress bar for skip mode episodes?

However, I did the exact same test with an episode of Bob's Burgers and everything behaved as it was supposed to and left the Bob's Burgers episode at the one minute mark and did not start playing after the skip mode finished processing the episode. Here is the kicker, I did the same exact test again on the exact same Supernatural episode as before and it worked the way it was supposed to! So, I'm not sure what's going on. :)

I'll keep an eye out the next few days and see if the behavior stays the same with skip mode episodes now that the TiVo has been rebooted. If so then I'll send some logs your way. Thanks for all your help.

**Comment by mackworth** [comment]
There are some timing parameters that may be at play here, so let me know if you see any correlation on issues. BTW, which TiVo do you have?

**Comment by scottsisco** [comment]
Will do. I have the TiVo Roamio Plus.

**Comment by scottsisco** [comment]
cTiVo has worked exactly as it is supposed to automatically encoding 5 skipmode shows without changing the progress bar for the shows on the TiVo.

However, I have discovered what is causing the progress bar issues at least on my TiVo. The progress bar changing to 100% viewed only occurs for me when I select an entire series in cTiVo and manually initiate grabbing all skipmode data for the series from the cTiVo interface. What is also rather unpredictable about the whole thing is it often does not move all skipmode episodes to 100% progress bar, but many of them. I will include some before and after pictures to better illustrate the point. I will also attach some logs as well.

I tested this on both a late 2012 Mac Pro (Mojave, cTiVo 3.3.0 ) and a late 2009 Mac Mini ( El Capitan, cTiVo 3.3.0) and found similar results.

Walking Dead **Before** Manually running Skipmode for Series from Mac Pro
![image](https://user-images.githubusercontent.com/7456282/55174861-78049f80-513b-11e9-859e-794567c30558.png)

Walking Dead **After** Manually running Skipmode for Series from Mac Pro
![image](https://user-images.githubusercontent.com/7456282/55174985-b39f6980-513b-11e9-9cf9-4cc6b625470c.png)

Note the changes in progress between the before and after images for episodes "Scares" and "Chokepoint"
Logs: [mac-pro-com.cTiVo.cTiVo 2019-03-28--01-49-45-897.log](https://github.com/mackworth/cTiVo/files/3019376/mac-pro-com.cTiVo.cTiVo.2019-03-28--01-49-45-897.log)


Bob's Burgers **Before** Manually running Skipmode for Series from Mac Mini
![image](https://user-images.githubusercontent.com/7456282/55175117-f06b6080-513b-11e9-88bd-e675e7338422.png)

Bob's Burgers **After** Manually running Skipmode for Series from Mac Mini
![image](https://user-images.githubusercontent.com/7456282/55175176-0842e480-513c-11e9-82a7-9fba939a9e10.png)

Note changes in progress between the before and after images for episodes "Every Which Way But Goose" and "Roamin' Bob-iday"
Logs: [mac-mini-com.cTiVo.cTiVo 2019-03-28--02-03-22-361.log](https://github.com/mackworth/cTiVo/files/3019379/mac-mini-com.cTiVo.cTiVo.2019-03-28--02-03-22-361.log)

With all this said, I did reboot the TiVo when you asked me to and I have not noticed any issues with any episodes recorded after the reboot. I wonder if the progress bar issue is isolated to episodes recorded before the reboot? Either way this is not that big of a deal for me as it will be a rare occurrence going forward that I will need to grab all of the skipmode data for an entire series manually since the nightly skipmode retrieval on a per episode basis seems to be working just fine.

**Comment by mackworth** [comment]
Thank you for the detailed notes.  I was therefore able to recreate on my system.  I also think that there's definitely a TiVo bug here...

Take any show (SkipMode or not) that hasn't been played; play at least 15 seconds, then hit left arrow (either once or twice) to go back to the series folder. It will correctly either show nothing or a tiny portion played, depending on how much you played. Now go back in and rewind to the beginning. Hit left arrow, and the progress bar will be filled in. If you go through the individual show page, you'll also see the difference there. If it's at least 15 seconds, it shows "Resume" and less than that, it shows "Play'. In fact, I haven't been able to get a show to go back to zero progress (without it being 15 seconds in, and showing Resume).

As cTiVo sets unplayed shows back to 0, that's what's triggering the bug here. OTOH, you're seeing cases where cTiVo isn't triggering the bug, so I'll have to experiment with what the difference is. I haven't managed to find a reproducible case, even doing a auto-retrieval. Judging from my inability to get it back to zero progress, I'm guessing once a show has been played (or Skipmode'd) it's then in some different state, so I'll have to wait until I get a new SkipMode show in a series folder to test the auto-retrieving scenario.

**Comment by scottsisco** [comment]
Thank you so much for your hard work!

**Comment by mackworth** [comment]
Spent quite a while on this, and came to the conclusion that there's something random going on inside the TiVo. Whether on manual or automatic, I can run SkipMode on a show multiple times, and have it not set the blue progress bar, then the next time it does. I did a group of six and it didn't set any 2 times, then 1/6, then all of them. If anyone can come up with a pattern of behavior, I'm happy to look at it some more, but for now, as it does seem to happen much less on auto-mode, I'm inclined to ignore it.

**Comment by scottsisco** [comment]
Thanks for taking the time to look at it! I will use auto-mode 95 percent of the time so this is not that big of a deal for me in the end.
