### ISSUE TITLE
Can prematurely ended recordings be problematic for cTiVo?

### ISSUE THREAD

**Issue by wjmt3** [mackworth/cTiVo#371]
I recorded a half-hour show but decided to stop recording 22 minutes in. The program (all 22 minutes of it) played just fine on the TiVo. When I transferred it with cTiVo (3.3.1b1), it seemed to finish early, though the message given was the usual "TiVo show transferred" message that one would see after an uneventful transfer.

The finished transfer was only 13:54 in length. I tried it again using Decrypted TiVo Show to rule out any encoding issues, and even temporarily reverted to 3.3.0. There was no change in outcome. Unfortunately, I no longer have the recording because I had to make room for a more important recording. No matter which settings I used, it always stopped at the same exact point, and cTiVo never indicated a problem. I wouldn't even know if I hadn't decided to play it back.

So while I can't really troubleshoot this particular issue,  for now I'd just like to know if my decision to stop the recording early could have resulted in a less than perfect recording that cTiVo couldn't handle completely gracefully? Ever seen behavior like that?

**Comment by mackworth** [comment]
I do a lot of short recordings during testing, and don't have any trouble with them; I think that was just a coincidence. On the other hand, there are frequently shows with glitches in the stream that apparently confound the not-very-robust encryption code in the TiVo, causing it to just stop converting the show. The transport doesn't report a problem, and if it's long enough, cTiVo will just accept it.  (Because of the transcoding, the byte count the TiVo reports is approximate, and so after a transfer, you'll see the size of the show get adjusted. It measures in bytes, not seconds, but if it's 70% of the original, then cTiVo adjudicates it to be close enough.) Now 22 minutes * 70% would be 15.4 minutes, but when added to an encoding discrepancy on the total size, it could have been just long enough to pass that test.

**Comment by wjmt3** [comment]
Yes, this was also the first such problem I've ever had.
