### ISSUE TITLE
cTV

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#384]
Looks like the Catalina is pushed to October. Never the less, I wanted to take a look at cTV. Can you tell where it is. A search of MAS resulted in no hits.

Thank You

**Comment by tdlivings** [comment]
Nevermind, I found it.

**Comment by tdlivings** [comment]
First pull of download queue resulted in a hang for cTV and com.apple.hiservices-xpcservice (444). Have to force quit.

Model Name:	iMac Pro
  Model Identifier:	iMacPro1,1
  Processor Name:	Intel Xeon W
  Processor Speed:	3.2 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	1 MB
  L3 Cache:	11 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB

System Version:	macOS 10.14.6 (18G95)
  Kernel Version:	Darwin 18.7.0
----------------------------------------------------------
Date/Time:       2019-09-14 18:46:12 -0700
End time:        2019-09-14 18:46:14 -0700
OS Version:      Mac OS X 10.14.6 (Build 18G95)
Architecture:    x86_64h
Report Version:  28

Data Source:     Stackshots
Shared Cache:    0x3ec0000 A333E572-D9C4-33BC-8139-A2AC455300F0

Command:         cTV
Path:            UNKNOWN PATH
Version:         ??? (???)
Parent:          launchd [1]
PID:             2036

Event:           hang
Duration:        1.70s
Steps:           17 (100ms sampling interval)

Hardware model:  iMacPro1,1
Active cpus:     16
[com.cTiVo.cTiVo 2019-09-14--12-53-31-360.log](https://github.com/mackworth/cTiVo/files/3613329/com.cTiVo.cTiVo.2019-09-14--12-53-31-360.log)

**Comment by testmack** [comment]
That’s impressive! And sorry about that.  Can you run it again, so it can push the crash result? And let me know if it does it the second time as well. 

If it does, then feel free to run the latest beta of cTiVo (which should bring your queue/prefs back to non-sandbox).

**Comment by testmack** [comment]
Oh, and if it’s not to late, set Debug level to Verbose before trying the queue again.

**Comment by tdlivings** [comment]
didn't crash this time. I restarted the unit to see if it was a mapping issue under the hood.

**Comment by tdlivings** [comment]
downloading now

**Comment by tdlivings** [comment]
[com.cTiVo.cTiVo 2019-09-14--12-53-31-360.log](https://github.com/mackworth/cTiVo/files/3613341/com.cTiVo.cTiVo.2019-09-14--12-53-31-360.log)

**Comment by mackworth** [comment]
Sigh. I guess because it was a hang rather than a crash, no report was apparently generated. Could you go into Console, and see if it generated any into?  check in system.log between 18:40:59 and  
18:47:28.

Also look in User Reports for any diagnostic reports there.

Oh, and you should turn Verbose off now.  Maybe leave it at Major.

BTW, the hang report above says it only lasted 1.7 seconds? I assume that is inaccurate.

There does seem to be some issues with com.apple.hiservices-xpcservice hanging in general.  See [here](https://forums.developer.apple.com/thread/113858) for instance. It is apparently related to " interfaces for accessibility, Internet Config, the pasteboard, the Process Manager, and the Translation Manager". So maybe launching a sub-process (such as cTiVo does when you start a download) is hanging?

**Comment by tdlivings** [comment]
Sorry for the delay. No crash spin dump report generated. And yes the hang was 3 minutes. Verbose off.

**Comment by tdlivings** [comment]
There is also a technical report that indicates a need for “restart after install is required after a install security prompt” going forward.   

I will do further testing later this week.

**Comment by mackworth** [comment]
Do you have a URL or reference on that?

**Comment by tdlivings** [comment]
A URL for what specifically?

**Comment by mackworth** [comment]
The technical report re “restart...” that you mentioned.

**Comment by tdlivings** [comment]
email white paper to aol.com

**Comment by mackworth** [comment]
Ok, thanks.  I’ll mark this as done for now, hoping it’s just cosmic rays/beta, but obviously let me know otherwise. Or if anyone else sees a similar problem!
