### ISSUE TITLE
cTivo Dropping all TV Shows in the Download Folder root path

### ISSUE THREAD

**Issue by blankgm** [mackworth/cTiVo#395]
Took a look at my system tonight and noted that cTivo has been dropping TV Shows (not movies) into the root download path with filenames that are missing the first half of the filename elements.

Example:
Restaurant Impossible - S13E05 - Ambush Out of Control - (164 - Food-E) 

was saved as:
 -  (164 - FOOD-E).mp4

Using the following template, which I haven't changed in years:
["TV Shows" / Main Title / "Season " Season | Year / MainTitle " - " SeriesEpNumber | OriginalAirDate ["-" ExtraEpisode][" - " EpisodeTitle | Guests]]["Movies"  / MainTitle " (" MovieYear ")"] -  ([ChannelNum] - [Channel])

I am currently manually renaming the files, but if you can see what I am doing wrong here - I sure would appreciate a heads up.

**Comment by mackworth** [comment]
You've got an unfortunate space between Main and Title near the beginning. That gives it an unknown keyword Main (title happens to be a real keyword), which causes the entire conditional (from ["TV shows" ...Guests]] to fail returning nothing, and it's not a movie, so that leaves the -(channelNum-channel) part.  Remove that space and you should be fine.  (Note that you can select a few shows, and then use the last entry in the keyword pulldown to test the current template on the selected shows, rather than waiting to do some downloads.)

**Comment by blankgm** [comment]
Thanks.  Wonder how that sneaked in.  I keep a backup text version of my keyword settings.  Maybe a helpful autocorrect during the last upgrade.

Thanks again.  Hopefully that will do it.

**Comment by mackworth** [comment]
I'll assume that works, but let me know otherwise. 

BTW, thanks for the question. While empty keywords are supposed to silently fail (e.g. no MovieYear causes the Movie clause to be empty), invalid ones have also been doing that, which seems wrong in retrospect. For example, I had to go back to the source to figure out what was wrong here.. 

So I've added an error msg in the log and in the filename to make it much more obvious:
In this case,  instead of creating:
>  (1008 - KGWDT).mp4

the next version would now create:
>  TV Shows/(UNKNOWN KEYWORD-'Main')The Good Place: Help is Other People/Season 04/The Good Place - S04E07 - Help is Other People - (1008 - KGWDT).mp4
