### ISSUE TITLE
Increasing amount of failed downloads

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#413]
I can remember very recently when I very rarely had a download failure. Now it is happening weekly and on different channels and shows. Perhaps the TiVo people made a programming change to the software?

Here is a log but it looks like an old bug rearing its head again. (Invalid MAK -- aborting)

[com.cTiVo.cTiVo 2020-03-28--05-01-02-742.log](https://github.com/mackworth/cTiVo/files/4396655/com.cTiVo.cTiVo.2020-03-28--05-01-02-742.log)

**Comment by kralc3292** [comment]
Respectfully, I'm also having similar issues with downloading HiDef shows via cTiVo.  SD format downloads fine, varying channels, but the HD versions of the same show intermittantly fail in wider scope since what seems to have been mid-December 2019, especially CW shows, which used to never fail. Prior, cTiVo appeared to have ben rock solid?  PRAM cache clear on Mac side doesn't seem to help. MacOS Catalina version 10.15.4, iMac Retina 5K, 16MB, 4.2 Ghz.  5 year old Roamio with cable card and Comcast.

[com.cTiVo.cTiVo 2020-04-09--16-46-17-232.log](https://github.com/mackworth/cTiVo/files/4458156/com.cTiVo.cTiVo.2020-04-09--16-46-17-232.log)

Respect / Appreciate all the effort that's gone into cTiVo. I sincerely wish I had this kind of coding talent.   -K

**Comment by tdlivings** [comment]
It seems to be a TiVo issue not CTiVo. Looking at the TiVo information I am getting missing srt files, missing skip and now a boat load of corrupted recordings. Noting lasts forever eh?

**Comment by kralc3292** [comment]
> Hi tdlivings,


What’s your take on the Comcast cable card going bad?
I ask, because my local Comcast, has a new series of channels at an even higher number and I can’t record those either. For example, local to Denver, channel “2" was always KWGN , sister station to WGN in Chicago. My Comcast high def channel is number for KWGNDT is 656 - which used to work religiously with cTiVo. And as of the past year, there’s now a KWGNHD #1002.

Or is that just wishful thinking and a new TiVo is in order?

The DVR/recorded show is there on the TiVo, complete, I just can’t down load it to my iMac.

And thanks for replying. I appreciate the follow up.
-Kent in Denver

**Comment by mackworth** [comment]
Unfortunately, this looks like a cable company/TiVo issue. There seems to be increasing numbers of corrupted files. TivoCommunity has a number of discussions about this. The download process is very sensitive to these issues, so sometimes it translates to an inability to download beyond a certain point, other times the decryption process fails.  Not much we can do at the receiving end of the chain.
