### ISSUE TITLE
SSLLLOOOWW

### ISSUE THREAD

**Issue by antealtares** [mackworth/cTiVo#414]
Hi there!

I love love love ctivo, bbut lately,  mine has been running VERY slow. Like, 6 hours for a 1 hour episode. I've been using "Default" which I had been using very successfully before. Any ideas of what might be going wrong? Could it be a settings issue or my Tivo Roamio Pro just getting slower?

**Comment by antealtares** [comment]
[com.cTiVo.cTiVo 2020-04-10--21-14-29-442.log](https://github.com/mackworth/cTiVo/files/4466641/com.cTiVo.cTiVo.2020-04-10--21-14-29-442.log)

There is a moca with tivo minis connected, but theyd ont' really work anymore.

**Comment by mackworth** [comment]
So, It looks to me like you're having network issues of some sort: As you can see below, for the four shows in the log, they are taking 3-5 hrs each to transfer. In addition, two of them failed entirely during transfer and had to retry. OTOH, the conversion times are reasonable. 

So, obviously the first place to start is to reboot your Mac, Minis, and your TiVo, maybe even your network router/wifi. Second, if you're using the MOCA to get to the Mac, maybe try disconnecting the "not-really-working" Minis?  Any way to test your network otherwise (peer-to-peer file transfer between Macs or others?) Could the problem with Minis also be a symptom of a network problem?

You can see the throughput in your browser by clicking the following link: 
[Batwoman](http://dvr-4226.local.:80/download/Batwoman.TiVo?Container=%2FNowPlaying&id=250534)  You'll need to use "tivo" as the username, and your MAK as the password.  It should be doing about 7MB/minute.  
```
			Start Time 	Downloaded 	Converted
Batwoman:  		17:14   	22:22  		23:10 
Oprah: 			22:24 		3:00 		4:18 
Tamron Hall (12/6): 	 3:01 		4:18		(failed)
Tamron Hall (12/6): 	 4:19		7:37 	 	7:45
Tamron Hall (12/7): 	 7:38 		7:41  		failure
Tamron Hall (12/7): 	 7:41 		unknown		14:06

Total Time: 		Download 	Conversion
Batwoman:  		 5:08   	1:08  		
Oprah: 			 4:06 		1:18		
Tamron Hall (12/6): 	 1:18 Fail 	N/A		
Tamron Hall (12/6): 	 3:18		0:08 	 	
Tamron Hall (12/7): 	 0:03 Fail 	N/A
Tamron Hall (12/7): 	 unknown   - 6:25 for xfer and convert

```

**Comment by antealtares** [comment]
Hi there! Thank you so much for responding. I really appreciate you taking the time!

I bet you are right that it's a symptom of a network error, but I'm not sure how to fix that. I tested out the throughput and found it was downloading about 4.3mb/minute. Do you know of any common issues that might cause this? I will try doing a TiVo reset. I only connect to the tivo box on my Mac through wireless network. I did have the Moca set up and the Tivo minis worked great for 2.5 years. But then all of a sudden we started getting network errors on them that would interrupt service before it would come back and then a few minutes later, it would happen again.

**Comment by antealtares** [comment]
OMG! I just swapped out the ethernet cord and it changed to 25mb/min!!!! I'll give this downloading with cTIVO again!

**Comment by mackworth** [comment]
I take it it's still running great, so I'll close this.

**Comment by antealtares** [comment]
Yes!! Just had to switch Ethernet cables and now it's back to perfect.
Thank you!!
