### ISSUE TITLE
Downloads just keep failing....

### ISSUE THREAD

**Issue by rwheeler56** [mackworth/cTiVo#428]
As previously reported, and where someone else jumped on my issue/post, I continue to have intermittent issues with downloading/converting TV shows from my Tivo Bolt.  It is random, where week the show will download/convert successful and then the next week it will fail, and then next week it will fail and then the work after it will work.  I'm not sure if Tivo has put something into their code to screw things up with the cTiVo or if it is Xfinity doing something with the code in the shows or what, but this problem has just gotten worse and I'm starting to think that before it ever gets better, or fixed, that Tivo might be part of our history anyway (here is to hoping that never happens, but one never knows).  Here is the link to my previous issue/post that got hijacked by someone else reporting their issue that "may" have been the same issue but maybe not and thus attention what directed towards his issue and mine seems to have gotten forgotten about......https://github.com/mackworth/cTiVo/issues/405

**Comment by mackworth** [comment]
You're right; I hadn't noticed the name had changed. Can you re-run one of the ones that failed with Debug mode set to Detail, and post the log here?

**Comment by rwheeler56** [comment]
I believe one of these should be the log file.  Please let me know if you need anything further or if these are the correct log file(s).

[com.cTiVo.cTiVo 2020-10-10--17-16-57-096.log](https://github.com/mackworth/cTiVo/files/5365231/com.cTiVo.cTiVo.2020-10-10--17-16-57-096.log)
[com.cTiVo.cTiVo 2020-10-11--22-25-52-973.log](https://github.com/mackworth/cTiVo/files/5365234/com.cTiVo.cTiVo.2020-10-11--22-25-52-973.log)

**Comment by mackworth** [comment]
So, you're getting the error message `2 frames left in the queue on closing`. This is a known problem in the encoder we use (ffmpeg) for the last several years, see [bugtracking here](https://trac.ffmpeg.org/ticket/6375).  A possible workaround is to increase max-muxing_queue_size from the amount we already use (4000).  

 [Here's a Format](https://github.com/mackworth/cTiVo/files/5388037/MaxQueue.plist.zip) that you can use that will do that.  Download and uncompress the file, then use cTiVo's File>Import Formats command to load it.  Then download the same program using this Format.  If that works, great; let me know. If not, try using the Format HB Default instead for the file; which uses Handbrake instead of ffmpeg.

**Comment by rwheeler56** [comment]
Okay.  So, let me make sure I understand.  After i download and then import this formant I then reschedule the download of the show that failed and then let you know the outcome.  I don’t have to do anything else after I import the format, and then reschedule the download, is that correct ?

**Comment by mackworth** [comment]
Not quite. You’ll need to select the new Format. You can still use reschedule, just stop the Queue with Cmd-U, reschedule, change to the MaxQueue Format, and then start it again. Be sure it’s on Major Debug level.

**Comment by rwheeler56** [comment]
Eureka !!!  It worked !!!.   Before I completely jump up and down for joy, I am going back thru my list of show failures and seeing if they now download successfully.  I will definitely keep you posted !

**Comment by mackworth** [comment]
Great to hear. Let me know if the remaining ones are better.  I increased the Default queue number in the beta release, so if you could try that, it would be great.
