### ISSUE TITLE
Download Always Fails with Brand New Edge on MacBookPro 2019 (BigSur)

### ISSUE THREAD

**Issue by marvinbass** [mackworth/cTiVo#450]
I just bought the Tivo Edge to hope to be able to download and safe Shows/Movies on my Mac. I found out the Tivo does not offer this anymore. :( so I found your App. I have tried every format and no luck downloading. The Edge is connected Via Ethernet to an Apple Airport Express within the wireless network. I am using the latest OS 11.2.1
I have tested using Tivo's app on my iPhone to see if the recording would stream and it did with no problem. It's more than likely something in Edge is not allowing it to download content. Please Help.

**Comment by mackworth** [comment]
What happens when you try to download? Does the Edge crash, or you just get an error in cTiVo?  If the crash, then check your TiVo's software version. It needs to be at least 21.9.7.v3-USM-12-D6F

If you just get an error, can you set Debug Level to Detail, then try another download. After it fails, then use `Help>See logs in finder`. Then compress the cTiVo directory using a Control-Click on it in the Finder and select Compress. Then post the result .zip file here.

**Comment by marvinbass** [comment]
Hi mackworth,
Edge does not crash, just get failed DL in cTiVo.
I have TiVo version 21.10.2.v11-USM-12-D6F
OK I am currently recording a show right now. I'll attempt again and send you the log.
Thank You for responding!

**Comment by marvinbass** [comment]
Here Ya Go!
[com.cTiVo.cTiVo 2021-02-12--07-07-18-808.log.zip](https://github.com/mackworth/cTiVo/files/5970325/com.cTiVo.cTiVo.2021-02-12--07-07-18-808.log.zip)

**Comment by mackworth** [comment]
Try rebooting your TiVo and see if that fixes it. If not, please submit the updated log again.

**Comment by marvinbass** [comment]
I did reboot TiVo early today due to another issue. I'll do all this tomorrow. Thank You

**Comment by marvinbass** [comment]
Hi macworth,
I did what you asked. I rebooted Tivo and attempted to DL a 30min show. It Failed once again after
[com.cTiVo.cTiVo 2021-02-12--07-07-18-808.log.zip](https://github.com/mackworth/cTiVo/files/5974492/com.cTiVo.cTiVo.2021-02-12--07-07-18-808.log.zip)
 several retries.

**Comment by mackworth** [comment]
Looks like it might be a network problem as you're getting anywhere from 25 to 80% of the show downloaded before the connection times out.  Quit cTiVo and try clicking on this link in Safari:

http://dvr-7476.local.:80/download/NBC4%20News%20at%2011am.TiVo?Container=%2FNowPlaying&id=26

You'll probably need to give it user `tivo` and password is your MAK. See if it can download the whole show.  (It's about 3GB, so be sure to delete any attempts afterwards).

**Comment by marvinbass** [comment]
Ok, Starting the DL now.

**Comment by marvinbass** [comment]
Apparently Tivo went black and started up again. I guess that means Tivo crashed? It stopped at 441.6MB downloaded

**Comment by mackworth** [comment]
Yup, that's a crash.  I hesitate to suggest, but you should probably try it again. 

FYI, This is the mechanism that cTiVo calls to get the file, and then it does the various processing on the Mac.  If we can't get the file through this process, there's not much we can do.  For a while, all the Edge's were crashing when we retrieved a show, but the version I mentioned fixed that problem, and yours certainly looks later than that one. You can try this one as well: 

Note that you need to wait a minute between trying to get a file. Their downloader has always been sensitive to multiple
attempts and can crash (just the process, not the TiVo) if you do it too soon. Thus cTiVo does a little countdown before each show.  Somehow this got triggered anyways in your case, so all the Clarice downloads (from 2/11 11:08P to 11:53) failed due to that problem. (BTW, you should have gotten a msg `TiVo Warning: Server Busy. If this recurs, your TiVo (TiVo DVR) may need to be restarted`?) The reboot fixed that problem, but now all the NBC news shows are only partially downloading.

**Comment by marvinbass** [comment]
Well.. while I was out doing some errands my wife told me that TiVo crashed again and just shutdown. 
I have restarted it again. This sucks because my modem and router is on the other side of the living room that why I went with using a Apple Airport Express via Ethernet. The built in wireless on the TiVo Edge is even worse. I couldn’t even stream TiVo+!
I guess I’ll have to pull out a longer Ethernet cable to run directly into the router. I’ll get back to you once I try that. 
Thank you for your time and help on this. 

After thought:?do you think TiVo has changed the OS so these types of transfers are blocked??
Have you tested the version that I have in the Edge??

**Comment by mackworth** [comment]
do you think TiVo has changed the OS so these types of transfers are blocked??
No, the symptoms would be more dramatic. We’ve been in this benign neglect period for about a decade. (No formal support, but they keep it working)

Have you tested the version that I have in the Edge??
No, (I don’t actually have an Edge), but lots of cTiVo users do, and I’ve heard no other complaints since that release I mentioned fixed their launch bug.

**Comment by mackworth** [comment]
closing for now. let me know if you still have a problem.

**Comment by marvinbass** [comment]
Sorry been busy. I still need to do a direct ethernet connection to test. I'll get back to you soon.
