### ISSUE TITLE
Show won't download from Roamio

### ISSUE THREAD

**Issue by ubragg** [mackworth/cTiVo#453]
I've had plenty of successful downloads, but one episode of a show fails every time.  It downloads successfully and then gets all the way to 100% Encoded and then it fails and starts over.  I've tried different options, rebooting the TiVo, etc.

Log is attached.  Any suggestions?

[com.cTiVo.cTiVo 2021-02-22--21-03-47-785.log](https://github.com/mackworth/cTiVo/files/6025932/com.cTiVo.cTiVo.2021-02-22--21-03-47-785.log)

**Comment by mackworth** [comment]
Couple things to try. ffmpeg is complaining that the file is damaged.

 There's a known bug in ffmpeg that may the problem here.  To try a potential fix, you'll need to create a user Format:
1) Go to Edit>Format
2) select Default, 
3) hit Duplicate
4) change the name to `Default maxQueue`,
5) add ` -max_muxing_queue_size 99999 ` in VideoOptions before `-vcodec`
6) hit Save and Done

Then change your Video Format (upper-right corner) to `Default MaxQueue` and try your show again.  Make sure the format in the queue is correct.

Alternatively, you could try a HandBrake conversion instead. (Go into Edit>Format, select `HB Default` and tick `show in User Interface` to enable it).

Let me know if either of these work.

**Comment by ubragg** [comment]
The maxQueue trick worked, thanks for the quick solution!

**Comment by ubragg** [comment]
It turns out I spoke too soon.  When I went to watch the episode that successfully downloaded using the maxQueue trick, it just had audio with no video (and the file was much smaller than normal).

I then tried the HandBrake suggestion, which also seemed to succeed, but then the video was just a gray box with audio playing.

I'm guessing there must be something weird with this particular episode, as all the other ones have been just fine.  And this one plays fine on the TiVo, too.

If you don't have any other ideas and want to chalk this up as a strange one-off, feel free to close this, but I'm happy to keep trying if you have more thoughts or want to understand it better.

**Comment by wjmt3** [comment]
@ubragg, you're not alone! I'm having _very_ similar problems, also with a Roamio....the show plays fine, but will not download or encode properly. I already use Handbrake, because I prefer it. The show downloads, then goes to encoding, but displays no progress, and finishes a few minutes later....This leaves a file that is only a couple hundred megabytes, when it should be at least a couple gigabytes...and it has a gray box with audio playing.

**Comment by mackworth** [comment]
That particular symptom (~10% size and audio only) is usually a result of trying to download an H.264 file over a Program Stream(PS). It should detect that automatically, switch to Transport Stream and retry. You can look in the log and see if that's what's happening (or I'm happy to interpret if you want to post it).

One way that might happen is if the channel's `Use TS` box is marked as Off in Edit Channels.

**Comment by wjmt3** [comment]
I went and explicitly checked the Use TS box for the channel and then retried an episode that hasn't been working. The log is attached. FWIW, the episode plays flawlessly on the TiVo.
[com.cTiVo.cTiVo 2021-03-16--19-56-45-768.log](https://github.com/mackworth/cTiVo/files/6151959/com.cTiVo.cTiVo.2021-03-16--19-56-45-768.log)

**Comment by mackworth** [comment]
Sorry, should have asked you to increase the logging level to at Detail

Also, that log shows that captioning failed, and reading their source code, that error indicates that the file starts off bad on the very first byte of a node, possibly even at the very start of the file. So that's suggesting it's not a normal corrupted stream (which would usually be in the middle of a node).  So maybe increase the logging to Detail, try again, and then turn captioning off, try once more, and post the resulting log. 

(If it does launch successfully the second time, you can switch logging to Major after a few seconds to avoid overloading the log file.)

**Comment by wjmt3** [comment]
Here's the resulting log file:

[com.cTiVo.cTiVo 2021-03-16--19-56-45-768 2.log](https://github.com/mackworth/cTiVo/files/6152257/com.cTiVo.cTiVo.2021-03-16--19-56-45-768.2.log)

**Comment by mackworth** [comment]
That's what I meant.  So that worked, right? File is playable? 

If so, that looks like ccextractor has a problem with that file, even though handbrake converted it just fine. If you feel like submitting it to them, they might be interested.   https://sampleplatform.ccextractor.org/account/

**Comment by wjmt3** [comment]
Hi Hugh,

I should have been more detailed in my reply. Unfortunately not. It failed identically to all the other attempts, with a total size of 249.5MB. It is audio only....  After it downloaded, it said "Encoding", but lacked a progress bar or any sort of percentage. Nonetheless, about a minute, the show was pronounced transferred.

**Comment by mackworth** [comment]
Interesting. So, I see that it is a TS, that it has a video and audio stream, it's not abnormally ending, but you're only getting a portion of the file. If you could do a download with Format of `Decrypted Tivo Show` to get the pre-conversion file.  

Then o you have mediaInfo? If not, it's [here](https://mediaarea.net/download/binary/mediainfo/20.09/MediaInfo_CLI_20.09_Mac.dmg): This will give me more info about what's inside the file. If you could run it both on the output file (.mp4) and the source file (the output from Decrypted download.

**Comment by wjmt3** [comment]
Interesting indeed. Here's the output for both:

[mediainfo mp4.txt](https://github.com/mackworth/cTiVo/files/6152756/mediainfo.mp4.txt)

[mediainfo ts.txt](https://github.com/mackworth/cTiVo/files/6152757/mediainfo.ts.txt)

**Comment by mackworth** [comment]
That's one messed up file. As you can see in the .ts version, it's claiming to have 18hrs of video at 44GB, even though the total file is marked as 60 minutes. It has 3GB of space, but although it has video and audio tracks, the converted file has exactly 67 milliseconds of video (ie. two frames), and ccextractor also says it's junk from the beginning. The converted size is equal to the downloaded audio (AC-3) of 165M plus the derived stereo version (AAC) of 70MB.  

So, you could try ffmpeg Format like Default, but it's pretty clearly trash, and not much we can do with it.

**Comment by wjmt3** [comment]
Thanks, Hugh. This is NOT a good week for me in terms of TiVo issues. I have several other individual episodes (of different shows, on different channels) that did similar things. I hope I don't have to be worried about the longevity of my Roamio. Others transfer just fine. I wonder if it would be worthwhile sending any of those your way? The oddest thing about all of this is that the file, as messed up as it is, plays absolutely perfectly on the TiVo itself.

And then, there's my Premiere, which hasn't connected to the TiVo service successfully since 3/11. Apparently, it happened back in January for some, but it's a first for me:

https://www.tivocommunity.com/community/index.php?threads/my-premiere-xl4-cant-complete-connect-to-tivo-service-now.581442/page-3

**Comment by mackworth** [comment]
Sigh. TiVo seems to have given up entirely. It’ll probably degrade more Snd more from here on.
