### ISSUE TITLE
cTivo 3.4.3 "hangs" on startup, but really bombs with out-of-memory

### ISSUE THREAD

**Issue by WilliamsJD** [mackworth/cTiVo#470]
My 16GB Catalina Mac is terminating cTivo every time I try to start it with an out-of-memory / hung condition. The only way I can get out of this is to Force Quit.

I think the last time I had cTivo work I had queued up a larger number of downloads than I had ever run before, and I think it is picking up this queued backlog when I am starting the app. 

I will attach the log from the most recent run, but would I'd like to do is clear the queue before starting it. Would this just be a matter of truncating the SQLite3 database? What would the best procedure be here?

Thanks in advance. I love cTivo but I've been frustrated with this problem for a while now.
Jeff

**Comment by WilliamsJD** [comment]
[com.cTiVo.cTiVo 2021-12-01--21-34-17-657.log](https://github.com/mackworth/cTiVo/files/7637376/com.cTiVo.cTiVo.2021-12-01--21-34-17-657.log)

**Comment by mackworth** [comment]
Well, just when I think I've seen everything...

Not much unusual in the log.  TiVo "Bendy" is not responding properly, so it might stand a reboot, but that certainly shouldn't cause a problem. 

Queue is 176 items, but I don't see trying to start downloading anything.

All data is stored in prefs file, including the queue as a simple text array.  It's at ~/Library/Preferences/com.cTiVo.cTiVo.plist

If you don't care about the queue, You could try just renaming it, and restarting cTiVo. Most other prefs are pretty easy to recreate.

Alternatively, you could just delete the queue. plists are binary encoded, so you'll need a plist editor (e.g. Xcode)  or there's  [this one](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwj-s_nOz8P0AhV0LH0KHZWpBOkQFnoECAQQAQ&url=https%3A%2F%2Fapps.apple.com%2Fus%2Fapp%2Fplist-editor%2Fid1157491961%3Fmt%3D12&usg=AOvVaw1K5ENeczRX7MNns1gfPeQF) which I haven't tried. The queue itself is in the key "queue"; weird, I know. 

Or you could just post it here (maybe need to compress in Finder to get GitHub to accept it),  and I can delete the queue and send it back.

**Comment by jwilliams-shadowsoft** [comment]
That, of course, worked. I lost my MAK, but that was easy to replace (although I don't see how to get it from the latest version of the Tivo website). I'm sure I'll have to go through and double-check all the settings, but the queue is now empty and no more hang/OOM.

I don't know why I thought it was a SQLite3 queue....

**Comment by mackworth** [comment]
Good to hear. Can you post the old file here? I’d like to see what could have caused the problem?

**Comment by mackworth** [comment]
Oh, if you’re bothered by posting your MAK, you can email the file directly at Mackworth at aol dot com

**Comment by WilliamsJD** [comment]
Thanks, I will email it.

**Comment by vtrandal** [comment]
Hugh,

Thank you and everyone that contributes to cTiVo. It’s an absolutely
fantastic source code project. It makes owning TiVo Roamio’s and a 2013
iMac a lot of fun. I hope interest in cTiVo is strong and remains that way
as long as people have working TiVo boxes for cTiVo to interact with.

This year I had my first TiVo disk failure. After watching a few videos it
seems the fix is simple (just install a new drive and the TiVo device will
use it). I never upgraded my TiVos to the “new experience” (whatever that
is). Both of my TiVo Roamio’s are still running software version
20.7.4D.RC15-846-6-846.

Question: Is it possible to make my TiVos automatically remove TV channels
with low signal strength? My TiVos still have the “Add an App” feature way
at the bottom of the Apps menu. What is that for? How can that be used to
load an app that does anything useful towards removing TV channels with low
signal strength? I hope this makes sense.

I’ve asked TiVo support to implement this feature and I’m sure no one
understands my request. I’m hoping the cTiVo community does understand what
I’m requesting. I would like to help. Low signal strength is subjective. In
this new feature the user would pick a value for good signal strength. Any
channel with signal strength below that user supplied value would be
removed from the users channel list.

By the way, I have an old TiVo Stream device (with Ethernet port) that
enables recording and watching shows using the TiVo app for iOS. I thought
maybe I could use the iOS app to favorite channels with good signal
strength, but I cannot get that to work either.

Vincent Randal

PS
Please let me know if I should post any of this message to the cTiVo email
list. I meant this message to be a quick thank you, but it grew beyond that.

**Comment by mackworth** [comment]
So, looked at your plist. Nothing obvious; it wasn't corrupted badly, and all the values looked reasonable. 176 shows isn't a problem, I frequently run tests with more than that. I then ran ctivo using that plist, and it loaded fine. Obviously this isn't a recreation, as I don't have your hard drives or TiVo, but not at all clear what the issue was. After properly complaining about not having your directories, it then settled down to wait for your TiVo to answer, and then marked it as offline. Queue looks fine. settings look good.  So, I'm surprised that you had that problem, and glad that replacing the plist fixed it for you.

"Add an App" was for HME apps that let you run games and other things on your TiVo. Never very useful and no longer supported AFAIK. No, it definitely wouldn't allow controlling the TiVo itself like that.  Obviously TiVo does do a signal strength check when it does its OTA scan, but the threshold Is not changeable. And unfortunately, TiVo has clearly moved on and will not be making any DVR improvements as far as I can see.

Thank you for your nice thoughts. I appreciate it!  Any other problems, let me know...
