### ISSUE TITLE
Tivo Server Busy, does not download

### ISSUE THREAD

**Issue by puddle21** [mackworth/cTiVo#485]
cTivo suddenly failing at downloads. May or may not have coincided with MacOS update. 
I forget what the initial error was, but after restarting cTiVo, the error is now "TiVo Server busy"
The TiVo in question is only using 39% of the HD. 
I have attached the major log. Please help
[com.cTiVo.cTiVo 2022-05-25--01-38-28-920.log](https://github.com/mackworth/cTiVo/files/8767311/com.cTiVo.cTiVo.2022-05-25--01-38-28-920.log)
!

**Comment by mackworth** [comment]
The TiVo downloading process is quite fragile. For example, downloading two shows immediately after each other will crash it. cTiVo tries very hard to avoid triggering this, (e.g.“Waiting for TiVo” phase), but sometimes it happens. Simple to recover, but you’ll need to reboot the TiVo itself to restart its downloader. 

I don’t know if you had a different error before restarting, but the attached log only has the multiple errors of `TiVo Warning: Server Busy. If this recurs, your TiVo (Master Bedroom) may need to be restarted.`

let me know if that works for you.

**Comment by puddle21** [comment]
I did reboot the TiVo by unplugging. The server error persisted. 
I appreciate the help!
This is the log prior to the server busy error I believe
[com.cTiVo.cTiVo 2022-05-21--06-58-03-964.log](https://github.com/mackworth/cTiVo/files/8767621/com.cTiVo.cTiVo.2022-05-21--06-58-03-964.log)
.

**Comment by mackworth** [comment]
Surprising, that is. 

Looking at your prior log, you were getting many `Looks like cTiVo was frozen out for X,XXX seconds` . That can mean that your system needs rebooting, or that it was going to sleep during a download (another way to crash your TiVo download, because it gets confused when nothing answers). 

Check that `Disable Sleep during Downloads` is on in Preferences.  Then I would reboot your Mac, then restart cTiVo, then reboot your TiVo once again. (Once you get that message, there's no other recovery than to reboot the TiVo. )

Note, rather than power cycle, use the `TiVo>Reboot TiVo` command in `Window>TiVo Remote` (Cmd-2).  After it comes back up again and refreshes the list, try another download. Assuming you get the same error, post the resulting log.

**Comment by puddle21** [comment]
So it tries to download now, but fails around 33%. I've tried two different shows
[com.cTiVo.cTiVo 2022-05-25--01-38-28-920.log](https://github.com/mackworth/cTiVo/files/8775392/com.cTiVo.cTiVo.2022-05-25--01-38-28-920.log)
.

**Comment by mackworth** [comment]
Sounds like progress!

Looks like you're using a custom Format `DLiMac`? What's it for? 

Try a built-in one, like `Default`. In particular, DLiMac is using mencoder, which is a really old encoder, not recommended at all.

**Comment by mackworth** [comment]
Great to hear! Nothing wrong with a custom format, you can certainly modify to get the right dimensions/size, but now using ffmpeg or HandBrake.
