### ISSUE TITLE
Question RE 3.5.3

### ISSUE THREAD

**Issue by tdlivings** [mackworth/cTiVo#489]
I was wondering if the new 3.5.3 have the new handbrake CLI? I would like to bring it in but I wanted to be prepared for the update particulars

**Comment by mackworth** [comment]
It does not yet. I'd like to update the rest of the binaries as well, and that will take a bit.

**Comment by tdlivings** [comment]
Thank you for the information

**Comment by mackworth** [comment]
Now that I'm back at my desk, to further answer the "update particulars", 3.5.3 JUST has the new certificate, and an ability to add one manually. I wanted to get that included before moving the minimum version of MacOS to 10.13 (as required by HandbrakeCLI 1.5.1), so that folks on 10.11 or 10.12 could continue to run past December. 

There's a workaround for [using Handbrake 1.5.1 posted here](https://github.com/mackworth/cTiVo/issues/481#issuecomment-1127105682):
