### ISSUE TITLE
Crashing v3.4.5  - after May 12 2023

### ISSUE THREAD

**Issue by dmazzella--** [mackworth/cTiVo#517]
Just in the last few days (sometime after 12-May-2023 and this post, 15-May-2023), cTivo version 3.4.5 crashes just after starting. It begins to show the Now Playing list, then stops.  

I have an ancient (late 2009) MacMini I use almost exclusively for cTivo, running OSX 10.11.x Ex Capitan, but I've also I've tested with 3.4.5 on a Intel with the latest OSX 13. On that newer Mac, 3.6 beta and 

On OSX 13, cTivo v 3.5.3 and v3.6Beta works fine. but 3.4.5 crashes just like the 2009 Mini -- IF you clear the caches and prefs in the ~/Library/Application Support/com.cTiVo.cTiVo and ~/Library/Preferences/com.cTiVo.cTiVo.plist first!

I found that if I start 3.5.3 on OSX13, let it load, close and open 3.4.5, it works ok?!  

In the crash log, this line stood out:
2023-05-15 13:36:37:126 -[MTTVDB infoForEpisodeNamed:orSeason:andEpisode:inSeries:onAirDate:completionHandler:failureHandler:withSeriesIDCandidate:andEpisodeCandidate:]_block_invoke@476>TVDB Episode JSON type Error (should be Array): <null> for 353160

 
[cTivo-3.4.5-crash-Terminal-OSX13.txt](https://github.com/mackworth/cTiVo/files/11481794/cTivo-3.4.5-crash-Terminal-OSX13.txt)
[com.cTiVo.cTiVo 2023-05-15--19-25-37-282.log](https://github.com/mackworth/cTiVo/files/11481799/com.cTiVo.cTiVo.2023-05-15--19-25-37-282.log)

[cTivo-3.4.5-crash-Terminal.txt](https://github.com/mackworth/cTiVo/files/11481795/cTivo-3.4.5-crash-Terminal.txt)

**Comment by dmazzella--** [comment]
FYI, I deleted ~/Preferences/com.cTiVo.cTiVo.plist and restarted on the 2009 MacMini, and 3.4.5 
But I had to set everything up again, but it looks to be stable once again.

**Comment by mackworth** [comment]
I indeed saw your travails in the crash logger; thanks for reporting in though as it confirms my suspicion. 

The root cause is that TVDB just started sending some junk on certain requests from its older database. In the original TVDB code, I missed a JSON-syntax check, so the older code crashes on that particular junk. If you run it again, cTiVo will naturally ask for the same request, get the same result, and crash again. 

The newer code (3.5/3.6) accesses the version 4 TVDB database, which doesn't have this problem. So if you run 3.5, then it will get the right info for that show and cache it locally. if you THEN run 3.4, it'll use the cached version, so no crash. But if you delete the cache, then it will query version 3 DB and crash again. 

You're not alone, I'm seeing a few other people have hit this crash (although nobody before 5/12). I can recreate it by hitting Empty Cache in 3.4.5.  So I've created a version 3.4.6 that will ignore the bad info. Give it a try [here](https://github.com/mackworth/cTiVo/releases/tag/v3.4.6), and let me know if it fixes it for you.

**Comment by mackworth** [comment]
Let me know also if the RPC stuff works (e.g. the Remote control screen and instantaneous updates of theNow playing list when you add or delete a recording on TiVo)

**Comment by dmazzella--** [comment]
RPC - Remote, Play now on TiVo, Delete on TiVo, and updates to the Now Playing List all work.  Thanks!

**Comment by mackworth** [comment]
I've pushed this out to everyone, but I have literally no way to test the update works. 

Can you do me a favor: open 3.4.5 ([redownload here](https://github.com/mackworth/cTiVo/releases/download/3.4.5/cTiVo.app.zip) if you have to) and confirm that you get the "Update available"? If so, then go ahead and update it with that button?

**Comment by dmazzella--** [comment]
Yes, it shows the update to 3.4.6 is available on the ancient Mac mini. 

With 3.4.5 on my MBP running Ventura, I get the update required to 3.5.3.

**Comment by mackworth** [comment]
Awesome. There's a lot of fiddly little bits to ensure that the right client is offered the right version and that nobody's hacked it in between my generating and their downloading it. I usually get them wrong, so glad to hear it worked this time. 

Thanks again for reporting it; it makes it much easier to find/fix the problem.
