### ISSUE TITLE
cTiVo not reading skip mode info correctly

### ISSUE THREAD

**Issue by alecksjaycubd** [mackworth/cTiVo#525]
I have a few shows that have skip enabled on my TiVo but cTiVo isn't seeing that info. Is there anything I can do to get them in sync?

**Comment by mackworth** [comment]
So for those shows, the SkipData column is blank entirely, or white w/ green SKIP text? 

Are any shows showing the icon, or just a few missing it? 

Are you on the latest version of cTiVo (3.5.3 or later)? (because TiVo's certificate to get to data like that changed).  

In Settings>Advanced, set TiVoRPC to Detail and then reload a show that you know has it (Cmd Click on the show, then Reload All Data). Then Help>Show Logs in Finder, Cmd-Click-Compress on the latest log, then post the resulting zip file here. (Don't attach to an email as Github strips those).

**Comment by alecksjaycubd** [comment]
Running 3.6.1
Most are show correctly with the green box and white skip (after running Get Skip Mode) and only a few show no info even though my TiVo shows they have skip. 
I have a few that are white with green text and line showing the info retrieve failed. If there's a way to get those to try again that would be great. 
I set the RPC and restarted cTiVo. Then I tried the Reload All Info on two of them that have this issue. 
[com.cTiVo.cTiVo 2023-09-03--13-05-24-476.log.zip](https://github.com/mackworth/cTiVo/files/12506894/com.cTiVo.cTiVo.2023-09-03--13-05-24-476.log.zip)
![Screenshot 2023-09-03 at 1 42 13 PM](https://github.com/mackworth/cTiVo/assets/43893846/da71c336-7ade-4b9f-8492-96fd1b8d9458)

**Comment by mackworth** [comment]
Ah, I interpreted it the other way, that no shows were getting it.  

Looks you've found a bug in the ReloadAll routine. It doesn't currently reload the RPC data like I thought it did. I'll fix in next release. You can work around by hitting `Settings>Advanced Preferences>Empty Caches`, which will reload everything for ALL your shows. 

But that's a little brutal, so if you prefer, I've created an alpha 3.6.2 with that fix in it. You can [download it here](https://www.icloud.com/iclouddrive/0d6bZfINHgPFho4zFFlAcHDjA#cTiVo.3.6.2). You can either keep using it, or go back to 3.6.1 whichever you prefer. Just hit Reload All Info again on the relevant shows. If it doesn't work, then post the log again.

**Comment by alecksjaycubd** [comment]
Thanks. The Empty Caches worked well.  I did have a few encodes fail. is there a way to see what may have happened?

**Comment by mackworth** [comment]
Sure. ‘Help>View Logs in Finder’, then double-click on latest log, search for the the word Failed or the name of your show. It’ll show you the error messages from the encoder. However, I will add that most failures are due to glitches in the stream that may not affect playback on the TiVo, but seems to throw their encryption algorithm off. 

On the SkipMode, you had shows that were blank (and failed?) that were fixed by Empty cache?

**Comment by alecksjaycubd** [comment]
The empty cache just corrected the missing skip modes.
Two of them failed encodes, but as you said probably just the stream.
Just ran them all through and a few didn't cut the commercials even though they had green skip boxes. Anything I can do to improve that?

**Comment by alecksjaycubd** [comment]
all of my failed encodes have this...
2023-09-05 23:12:12:232 -[MTTask failedTaskCompletion]@243>Task encode failed
ERROR: avformatMux: track 0, av_interleaved_write_frame failed with error 'Invalid argument'

**Comment by mackworth** [comment]
That's a typical message I see when there's some junk in the stream. You might try ffmpeg or sw Handbrake (Default or HB Default Formats), but not much hope.

**Comment by mackworth** [comment]
I've posted a beta of 3.6.2 which fixes the RPC refresh problem. Let me know if it works for you.
