### ISSUE TITLE
Renewing kmttg certificate

### ISSUE THREAD

**Issue by ccdragone** [mackworth/cTiVo#530]

**Comment by mackworth** [comment]
Thanks for the reminder!  I'll generate a new version. 

In the meantime, here's the two files [cdata.zip](https://github.com/mackworth/cTiVo/files/15223714/cdata.zip) you need to download. They should auto-expand when you do. 

Then in the Finder, use Cmd-Shift-G to go to `~/Library/Application Support/com.cTivo.cTiVo` 
(Just to confirm, you should see `com.microsoft.appcenter` and `com.crashlytics` folders).
Drag the two individual files into that main folder. 
To be overly clear, not the .zip file nor the folder containing the files, and into `com.cTiVo.cTiVo`, not the subfolders.
>
> com.cTiVo.cTiVo
> ----cdata.p12
> ----cdata.password
> ----com.crashlytics
> ----com.microsoft.appcenter
> 
Restart cTiVo. Check if you can see the remote for your TiVo. If not, look in the log file for your last launch, search for `p12` and see if there's an error message.
It should say:
>Overriding default TiVo Certificate with file:///Users/USERNAME/Library/Application%20Support/com.cTiVo.cTiVo/cdata.p12

You should be good until January 2026.
After you get the updated version, you should delete the two files from that directory (only because they will continue to override the next release if you don't manually update at that time).

**Comment by mackworth** [comment]
New version is [available here](https://github.com/mackworth/cTiVo/releases).

 Let me know if it works for you (or doesn't!)

**Comment by ccdragone** [comment]
Greetings Hugh.

Downloaded cTiVo.3.6.3.zip.  I seem to recall that in December 2022  I had
to copy the cdata password to the lmttg folder but I do not see a password
file in the download so but that's about all I was able to do.

I use kmttg constantly and have become very dependant on it.  When
confronted with the first certificate issue, I searched for some
proprietary software that I could purchase or license that would perform
all of the same functions but when the fix came along, I abandoned the
search.

You reference 'cTiVo', and while I do not know anything about it, I suspect
that this may be what I have been looking for.  I would appreciate some
guidance, suggestions, or alternatives and underscore the fact that I am
not looking for 'freeware'!

Regards,
Charles

**Comment by ccdragone** [comment]
P.S.  I am Windows 10 based,

**Comment by mackworth** [comment]
Okay, so I see the confusion. 
cTiVo (where you have reported an “issue”) is a Mac-based open-source product to work with your TiVo, similar to kmttg.
So if you want to update your kmttg, just download the latest version here::  
https://github.com/lart2150/kmttg/releases/tag/v2.8-l

Yes, you could download the cdata files above and put them in the right places for kmttg, but easier to just download the latest version.

Hope it goes well…

**Comment by ccdragone** [comment]
Well I don't believe this!

Downloaded 2.8.1, copied the results to my existing kmttg folder and low
and behold I regained access to my TiVos.

Amazing - to say the least.  Thank you just seems like a gross
understatement, but thank you anyway!

Charles

**Comment by mackworth** [comment]
you're welcome. glad it's working.

**Comment by ccdragone** [comment]
You were kind enough to provide me with a renewal certificate for my
Windows kmttg one year ago.  Today, exactly one year later, kmttg fails to
run.  While I hate to bother you, I have have come to rely on kmttg for
managing all aspects of our TiVos and am trying to come up with a fix - if
there is one!

Any help or advice would be greatly appreciated.

Charles

**Comment by mackworth** [comment]
No problem; just download the latest kmttg (2.9)here:

https://github.com/lart2150/kmttg/releases/tag/v2.9-l

**Comment by ccdragone** [comment]
Thanks for the assistance.  One minor glitch.  Attempts to run the JAR
routine call for the presence of JAVAfx and the javafx-sdk folder in the
unzipped kmttg_v2.9.1 folder is empty.  I have tried to download javafx
from Oracle but no luck.  I guess I'm missing something.

Charles

**Comment by mackworth** [comment]
Looks like this is a known issue; see thread here:
https://github.com/lart2150/kmttg/issues/40

**Comment by ccdragone** [comment]
Java 8 update 451 excluded Javafx as will all future updates.  After
replacing update 451 with 441, kmttg_v2.9-1 is quite happy!

On last question.  When will the current certificate expire?

Thanks again for your continued assistance.

Charles

**Comment by mackworth** [comment]
11/17/2026

And it will let you know 90 days in advance

**Comment by mackworth** [comment]
Particularly for a program I’m neither involved in, or even use?

No problem; happy to help.
